name: Go

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        go-version: [ '1.20.x', '1.21.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version
      - name:  Go test
        run: go test *.go -v

